services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  neo4j:
    image: neo4j:latest # Use the latest Neo4J community edition
    container_name: neo4j_knowledge_graph
    ports:
      - "7474:7474" # HTTP port for Neo4j Browser
      - "7687:7687" # Bolt for Python driver
    #volumes:
    #  - neo4j_data:/data
    #  - neo4j_logs:/logs
    #  - neo4j_import:/import
    #  - neo4j_plugins:/plugins
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    restart: always

  event-engine:
    build: ./event-engine
    container_name: event_engine_service
    depends_on:
      - kafka
    volumes:
      - ./cassandra.db:/app/cassandra.db

  knowledge-graph:
    build: ./knowledge-graph
    container_name: knowledge_graph_service
    env_file:
      - .env
    depends_on:
      - kafka
      - neo4j