services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      # This checks if the port is actually open and accepting connections
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  neo4j:
    image: neo4j:2026.04.0 # Use the latest Neo4J community edition
    container_name: neo4j_knowledge_graph
    ports:
      - "7474:7474" # HTTP port for Neo4j Browser
      - "7687:7687" # Bolt for Python driver
    volumes:
      - neo4j_data:/data
      #- ./neo4j/data:/data
      #- ./neo4j/logs:/logs
      #- ./neo4j/import:/var/lib/neo4j/import
      #- ./neo4j/plugins:/plugins

    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_PLUGINS: '["apoc"]'
      # allow apoc to execute
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    restart: always
    healthcheck:
      #test: ["CMD-SHELL", "cypher-shell -u neo4j -p 'password' 'RETURN 1' > /dev/null 2>&1 || exit 1"]
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    #environment:
    #  - OLLAMA_NUM_PARALLEL=1       # Force it to handle one window enrichment at a time
    #  - OMP_NUM_THREADS=4
    #  - OLLAMA_FLASH_ATTENTION=1
    deploy:
      resources:
        limits:
          cpus: '12.0'          # Max number of CPU cores Ollama can use
    #    reservations:
    #      cpus: '2.0'          # Minimum cores dedicated when active
    healthcheck:
      test: ["CMD-SHELL", "ollama list > /dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 20s

  event_engine_service:
    build: 
      context: .
      dockerfile: event_engine_service/Dockerfile
    container_name: event_engine_service
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./cassandra.db:/app/cassandra.db
      - ./datasets/validate/lucene.sqlite3:/app/lucene.sqlite3
      - ./event_engine_service:/app/event_engine_service
      - ./shared_utils:/app/shared_utils

  knowledge_graph_service:
    build: 
      context: .
      dockerfile: knowledge_graph_service/Dockerfile
    container_name: knowledge_graph_service
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    volumes:
      - ./knowledge_graph_service:/app/knowledge_graph_service
      - ./shared_utils:/app/shared_utils

  enrichment_service:
    build: 
      context: .
      dockerfile: enrichment_service/Dockerfile
    container_name: enrichment_service
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_healthy
    volumes:
      - ./enrichment_service:/app/enrichment_service
      - ./shared_utils:/app/shared_utils

volumes: 
  ollama_data:
  neo4j_data: